### ISSUE TITLE
How to integrate the method with GQA?

### ISSUE THREAD

**Issue by NickGao96** [CStanKonrad/long_llama#18]
I have read the cross batch code and I see that the implementation is a modification to the Multi-Head Attention version of the LLaMA attention. But larger LLaMA2 model uses a GQA. So is it possible to further integrate the method with GQA?

**Comment by CStanKonrad** [comment]
Hi!
Thanks for your question!
We have not tested it, but following the main idea you can for each group of queries make them attend to their keys within the batch and keys that their group attends to in several other elements of the batch.
