### ISSUE TITLE
Where is the learnable temperature parameter in cross_batch_attention?

### ISSUE THREAD

**Issue by MarkYangjiayi** [CStanKonrad/long_llama#21]
Hi, in section B.2 of the paper it seems that before calculation of the softmax score, a learnable temperature is applied to the attn_weights, but I couldn't seem to find it in the cross_batch_attention code. Was this parameter removed for some reason? Thanks!

**Comment by CStanKonrad** [comment]
Hi!
Thank you for your question.
In the experiments with the smaller models (non-LLaMA ones), we have used the [meliad](https://github.com/google-research/meliad) codebase, which normalizes keys and queries. This repository contains the code for  LLaMA-based models, which do not normalize keys and queries, therefore we do not apply the learnable temperature. However, I see that it is not properly emphasized in the paper. Thanks for spotting it out!
